export const ERRORS = {
  NOT_FOUND: { http: 404, msg: "Ruta no encontrada" },
  INTERNAL: { http: 500, msg: "Error interno del servidor" },
  PROJECT_NOT_FOUND: { http: 404, msg: "Proyecto no encontrado" },
  TASK_NOT_FOUND: { http: 404, msg: "Tarea no encontrada" },
  DB_CONSULT_ERROR: { http: 503, msg: "Error consultando la base de datos" },
  EMAIL_SEND_ERROR: { http: 503, msg: "Error enviando el correo" },
  USER_ALREADY_EXISTS: { http: 409, msg: "El usuario ya existe" },
  USER_ALREADY_CONFIRMED: {
    http: 403,
    msg: "Ese usuario ya se encuentra verificado",
  },
  USER_NOT_FOUND: { http: 404, msg: "Usuario no encontrado" },
  USER_NOT_CONFIRMED: {
    http: 403,
    msg: "Usuario no verificado. Se ha enviado un nuevo correo de verificacion, revisa tu bandeja de entrada",
  },
  USER_NOT_IN_TEAM: { http: 404, msg: "El usuario no pertenece al equipo" },
  USER_ALREADY_IN_TEAM: { http: 409, msg: "El usuario ya pertenece al equipo" },
  CANNOT_ADD_MANAGER_TO_TEAM: {
    http: 409,
    msg: "No se puede añadir el gestor del proyecto al equipo",
  },
  ASSET_NOT_FOUND: { http: 404, msg: "Asset no encontrado" },
  TOKEN_NOT_FOUND: { http: 404, msg: "Token no encontrado" },
  TOKEN_NOT_PROVIDED: { http: 401, msg: "Token no proporcionado" },
  NOTE_NOT_FOUND: { http: 404, msg: "Nota no encontrada" },
  INVALID_TOKEN: { http: 401, msg: "Token inválido o expirado" },
  INVALID_CREDENTIALS: { http: 401, msg: "Credenciales inválidas" },
  INVALID_CURRENT_PASSWORD: { http: 401, msg: "Contraseña actual no válida" },
  INVALID_PASSWORD: { http: 401, msg: "Password incorrecto" },
  UNATHORIZED: { http: 401, msg: "No autorizado" },
  UNAUTHORIZED_ACTION: { http: 403, msg: "Acción no autorizada" },
} as const;
